### ISSUE TITLE
Can't remember Width and Height.

### ISSUE THREAD

**Issue by tangxiadi** [Petethegoat/WinScroll#3]
The software can't remember the Width and Height. Each time you open the software, the width and height are 800x600.

**Comment by Petethegoat** [comment]
Glad someone finds this useful! I'll look into adding this.

**Comment by Petethegoat** [comment]
Let me know if [v0.4](https://github.com/Petethegoat/WinScroll/releases/tag/0.4) has any issues!

**Comment by tangxiadi** [comment]
Just the software panel remembered the numbers, and the mouse activity range is still limited to 800x600 by default.

**Comment by Petethegoat** [comment]
Whoops! Fix for this is on the way.

**Comment by Petethegoat** [comment]
Apologies for that, [v0.5](https://github.com/Petethegoat/WinScroll/releases/tag/0.5) should fix it.
